<?php

namespace Drupal\drupalx_ai\Service;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Logger\LoggerChannelFactoryInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Service for creating AI-generated landing pages.
 */
final class AiLandingPageService {

  /**
   * The config factory.
   *
   * @var \Drupal\Core\Config\ConfigFactoryInterface
   */
  private $configFactory;

  /**
   * Constructs a new AiLandingPageService object.
   *
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager
   *   The entity type manager.
   * @param \Drupal\Core\Logger\LoggerChannelFactoryInterface $loggerFactory
   *   The logger factory.
   * @param \Drupal\drupalx_ai\Service\MockLandingPageService $mockLandingPageService
   *   The mock landing page service.
   * @param \Drupal\drupalx_ai\Service\AiModelApiService $aiModelApiService
   *   The AI Model API service.
   * @param \Drupal\drupalx_ai\Service\ParagraphStructureService $paragraphStructureService
   *   The paragraph structure service.
   * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
   *   The config factory.
   */
  public function __construct(
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly LoggerChannelFactoryInterface $loggerFactory,
    private readonly MockLandingPageService $mockLandingPageService,
    private readonly AiModelApiService $aiModelApiService,
    private readonly ParagraphStructureService $paragraphStructureService,
    ConfigFactoryInterface $configFactory,
  ) {
    $this->configFactory = $configFactory;
  }

  /**
   * Generates AI content for a landing page based on a description.
   *
   * @param string $description
   *   The user-provided description of the desired landing page.
   *
   * @return array|null
   *   An array of paragraph data generated by AI, or null if generation failed.
   */
  public function generateAiContent(string $description): ?array {
    $paragraphStructures = $this->paragraphStructureService->getParagraphStructures(TRUE);
    $prompt = $this->buildPrompt($description, $paragraphStructures);

    $tools = [
      [
        'name' => 'generate_ai_landing_page',
        'description' => 'Generate an AI-driven landing page structure with content',
        'input_schema' => [
          'type' => 'object',
          'properties' => [
            'page_title' => [
              'type' => 'string',
              'description' => 'Create title for the landing page',
            ],
            'paragraphs' => [
              'type' => 'array',
              'items' => [
                'type' => 'object',
                'properties' => [
                  'type' => [
                    'type' => 'string',
                    'description' => 'The type of the paragraph',
                  ],
                  'fields' => [
                    'type' => 'object',
                    'additionalProperties' => TRUE,
                    'description' => 'The fields of the paragraph with their values',
                  ],
                ],
                'required' => ['type', 'fields'],
              ],
            ],
          ],
          'required' => ['paragraphs', 'page_title'],
        ],
      ],
    ];

    $result = $this->aiModelApiService->callAiApi($prompt, $tools, 'generate_ai_landing_page');

    if (is_array($result) && isset($result['paragraphs'])) {
      // If paragraphs is a string, attempt to decode it.
      if (is_string($result['paragraphs'])) {
        try {
          $decodedParagraphs = json_decode($result['paragraphs'], TRUE, 512, JSON_THROW_ON_ERROR);
          if (is_array($decodedParagraphs)) {
            $result['paragraphs'] = $decodedParagraphs;
          } else {
            $this->loggerFactory->get('drupalx_ai')->error('Failed to decode paragraphs data: not an array after decoding');
            return NULL;
          }
        } catch (\JsonException $e) {
          $this->loggerFactory->get('drupalx_ai')->error('Failed to decode paragraphs JSON: @message', ['@message' => $e->getMessage()]);
          return NULL;
        }
      }

      // Validate the structure.
      if (!is_array($result['paragraphs'])) {
        $this->loggerFactory->get('drupalx_ai')->error('Paragraphs data is not an array');
        return NULL;
      }

      return $result;
    }

    $this->loggerFactory->get('drupalx_ai')->error('AI content generation failed or returned unexpected result');
    return NULL;
  }

  /**
   * Builds the prompt for the AI API.
   *
   * @param string $description
   *   The user-provided description of the desired landing page.
   * @param array $paragraphStructures
   *   The available paragraph structures.
   *
   * @return string
   *   The constructed prompt.
   */
  private function buildPrompt(string $description, array $paragraphStructures): string {
    $prompt = "Generate an AI-driven landing page structure with content based on the following description:\n\n";
    $prompt .= "$description\n\n";
    $prompt .= "CRITICAL: The page_title is required. Create a compelling and relevant title for the landing page based on the content.\n\n";
    $prompt .= "CRITICAL: The paragraphs field MUST be an array, not a string. Do not stringify the paragraphs array.\n\n";
    $prompt .= "Available paragraph types and their structures (in JSON format):\n\n";

    $prompt .= json_encode($paragraphStructures, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . "\n\n";

    $prompt .= "Understanding the JSON structure:\n";
    $prompt .= "- 'b' represents the bundle (paragraph type)\n";
    $prompt .= "- 'f' is an array of fields, where each field has:\n";
    $prompt .= "  - 't': field type\n";
    $prompt .= "  - 'n': field name\n";
    $prompt .= "  - 'r': required (boolean)\n";
    $prompt .= "  - 'c': cardinality (-1 for unlimited, or a positive integer)\n";
    $prompt .= "  - 'e': an example value for the field\n";
    $prompt .= "  - 'o': (for list_string fields only) an array of allowed options\n\n";

    $allowedParagraphTypes = $this->mockLandingPageService->getAllowedParagraphTypes('node', 'landing', 'field_content');
    $prompt .= "IMPORTANT: Only use the following paragraph types as top-level array of paragraphs:\n";
    $prompt .= implode(", ", $allowedParagraphTypes) . "\n\n";

    $prompt .= "CRITICAL REQUIREMENTS:\n";
    $prompt .= "1. The 'bullet' paragraph is never in the top level array of paragraphs.\n";
    $prompt .= "2. Use a variety of paragraph types, do not overuse the same types over and over.\n";
    $prompt .= "3. For fields named 'field_icon', you MUST only use valid Lucide icon names (e.g. 'arrow-right').\n";
    $prompt .= "4. When generating the landing page structure, ensure that ONLY the allowed paragraph types listed above are used as top-level paragraphs.\n";
    $prompt .= "5. Other paragraph types can be used as nested paragraphs within these allowed types if the structure permits.\n";
    $prompt .= "6. CRITICAL: Every paragraph MUST have a 'type' property that matches its intended type. This includes:\n";
    $prompt .= "    - Top-level paragraphs (hero, carousel, card_group, accordion, pricing, etc.)\n";
    $prompt .= "    - Nested paragraphs:\n";
    $prompt .= "      * Accordion items must have type: 'accordion_item'\n";
    $prompt .= "      * Cards must have type: 'card'\n";
    $prompt .= "      * Carousel items must have type: 'carousel_item'\n";
    $prompt .= "      * Pricing cards must have type: 'pricing_card'\n";
    $prompt .= "7. For entity reference fields, use appropriate existing entity names or IDs.\n";
    $prompt .= "8. For viewsreference fields, use existing view names and display IDs.\n";
    $prompt .= "9. For list_string fields, choose only from the provided options in the 'o' array. Use the machine names (keys), not the human-readable labels.\n";
    $prompt .= "10. In field_features_text do not include any characters for bullets, only plain text separated by new lines.\n";
    $prompt .= "11. Stat items should always have a title value.\n";
    $prompt .= "12. The text paragraph does not have a field_summary field.\n";
    $prompt .= "13. For logo collection limit max to 7 media items.\n";
    $prompt .= "14. For layout fields (field_hero_layout, field_text_layout, field_sidebyside_layout), use machine names like 'image_top' not 'Image Top'.\n\n";

    $prompt .= "Example structure (note that paragraphs is an array, not a string):\n";
    $prompt .= "{\n";
    $prompt .= "  \"page_title\": \"Our Amazing Service\",\n";
    $prompt .= "  \"paragraphs\": [\n";
    $prompt .= "    {\n";
    $prompt .= "      \"type\": \"hero\",\n";
    $prompt .= "      \"fields\": {\n";
    $prompt .= "        \"field_heading\": \"Welcome to Our Service\",\n";
    $prompt .= "        \"field_hero_layout\": \"image_bottom\",\n";
    $prompt .= "        \"field_summary\": \"We provide top-notch solutions for your needs.\",\n";
    $prompt .= "        \"field_media\": \"Technology\"\n";
    $prompt .= "      }\n";
    $prompt .= "    },\n";
    $prompt .= "    {\n";
    $prompt .= "      \"type\": \"pricing\",\n";
    $prompt .= "      \"fields\": {\n";
    $prompt .= "        \"field_title\": \"Our Pricing Plans\",\n";
    $prompt .= "        \"field_summary\": \"Choose the plan that works best for you\",\n";
    $prompt .= "        \"field_pricing_cards\": [\n";
    $prompt .= "          {\n";
    $prompt .= "            \"type\": \"pricing_card\",\n";
    $prompt .= "            \"fields\": {\n";
    $prompt .= "              \"field_title\": \"Basic Plan\",\n";
    $prompt .= "              \"field_eyebrow\": \"Most Popular\",\n";
    $prompt .= "              \"field_features_text\": \"Feature 1\\nFeature 2\\nFeature 3\",\n";
    $prompt .= "              \"field_suffix\": \"Starting at\",\n";
    $prompt .= "              \"field_link\": {\"url\": \"/basic-plan\", \"text\": \"Get Started\"}\n";
    $prompt .= "            }\n";
    $prompt .= "          },\n";
    $prompt .= "          {\n";
    $prompt .= "            \"type\": \"pricing_card\",\n";
    $prompt .= "            \"fields\": {\n";
    $prompt .= "              \"field_title\": \"Pro Plan\",\n";
    $prompt .= "              \"field_eyebrow\": \"Best Value\",\n";
    $prompt .= "              \"field_features_text\": \"All Basic Features\\nPro Feature 1\\nPro Feature 2\",\n";
    $prompt .= "              \"field_suffix\": \"Only\",\n";
    $prompt .= "              \"field_link\": {\"url\": \"/pro-plan\", \"text\": \"Upgrade Now\"}\n";
    $prompt .= "            }\n";
    $prompt .= "          }\n";
    $prompt .= "        ]\n";
    $prompt .= "      }\n";
    $prompt .= "    },\n";
    $prompt .= "    {\n";
    $prompt .= "      \"type\": \"carousel\",\n";
    $prompt .= "      \"fields\": {\n";
    $prompt .= "        \"field_carousel_item\": [\n";
    $prompt .= "          {\n";
    $prompt .= "            \"type\": \"carousel_item\",\n";
    $prompt .= "            \"fields\": {\n";
    $prompt .= "              \"field_title\": \"Happy Customer\",\n";
    $prompt .= "              \"field_summary\": \"This service has been amazing!\",\n";
    $prompt .= "              \"field_media\": \"Customer Photo\"\n";
    $prompt .= "            }\n";
    $prompt .= "          },\n";
    $prompt .= "          {\n";
    $prompt .= "            \"type\": \"carousel_item\",\n";
    $prompt .= "            \"fields\": {\n";
    $prompt .= "              \"field_title\": \"Another Customer\",\n";
    $prompt .= "              \"field_summary\": \"Best service ever!\",\n";
    $prompt .= "              \"field_media\": \"Customer Photo\"\n";
    $prompt .= "            }\n";
    $prompt .= "          }\n";
    $prompt .= "        ]\n";
    $prompt .= "      }\n";
    $prompt .= "    },\n";
    $prompt .= "    {\n";
    $prompt .= "      \"type\": \"card_group\",\n";
    $prompt .= "      \"fields\": {\n";
    $prompt .= "        \"field_title\": \"Our Services\",\n";
    $prompt .= "        \"field_card\": [\n";
    $prompt .= "          {\n";
    $prompt .= "            \"type\": \"card\",\n";
    $prompt .= "            \"fields\": {\n";
    $prompt .= "              \"field_title\": \"Service One\",\n";
    $prompt .= "              \"field_summary\": \"Description of service one\",\n";
    $prompt .= "              \"field_media\": \"Service Image\",\n";
    $prompt .= "              \"field_link\": {\"url\": \"/service-one\", \"text\": \"Learn More\"}\n";
    $prompt .= "            }\n";
    $prompt .= "          },\n";
    $prompt .= "          {\n";
    $prompt .= "            \"type\": \"card\",\n";
    $prompt .= "            \"fields\": {\n";
    $prompt .= "              \"field_title\": \"Service Two\",\n";
    $prompt .= "              \"field_summary\": \"Description of service two\",\n";
    $prompt .= "              \"field_media\": \"Service Image\",\n";
    $prompt .= "              \"field_link\": {\"url\": \"/service-two\", \"text\": \"Learn More\"}\n";
    $prompt .= "            }\n";
    $prompt .= "          }\n";
    $prompt .= "        ]\n";
    $prompt .= "      }\n";
    $prompt .= "    },\n";
    $prompt .= "    {\n";
    $prompt .= "      \"type\": \"accordion\",\n";
    $prompt .= "      \"fields\": {\n";
    $prompt .= "        \"field_title\": \"Frequently Asked Questions\",\n";
    $prompt .= "        \"field_accordion_item\": [\n";
    $prompt .= "          {\n";
    $prompt .= "            \"type\": \"accordion_item\",\n";
    $prompt .= "            \"fields\": {\n";
    $prompt .= "              \"field_title\": \"What services do you offer?\",\n";
    $prompt .= "              \"field_body\": \"We offer a wide range of services including...\"\n";
    $prompt .= "            }\n";
    $prompt .= "          }\n";
    $prompt .= "        ]\n";
    $prompt .= "      }\n";
    $prompt .= "    }\n";
    $prompt .= "  ]\n";
    $prompt .= "}\n\n";

    $prompt .= "Please generate a landing page structure using these paragraph types. Fill in realistic content for each field. Use a variety of paragraph types to create an engaging and diverse landing page, while adhering to the allowed top-level paragraph types. When you're done, call the generate_ai_landing_page function with the generated structure.\n";

    return $prompt;
  }

  /**
   * Creates a landing page node with AI-generated content.
   *
   * @param string $page_title
   *   Name of the landing page.
   * @param array $paragraphs
   *   An array of paragraph data generated by AI.
   *
   * @return string|null
   *   The URL of the created node, or null if creation failed.
   */
  public function createLandingNodeWithAiContent(string $page_title, array $paragraphs): ?string {
    $this->loggerFactory->get('drupalx_ai')->info('Starting to create landing page with title: @title', ['@title' => $page_title]);

    try {
      // Log the node creation data
      $this->loggerFactory->get('drupalx_ai')->debug('Creating node with data: @data', [
        '@data' => json_encode([
          'type' => 'landing',
          'title' => $page_title,
          'field_hide_page_title' => 1,
          'status' => 1,
        ])
      ]);

      $node = Node::create([
        'type' => 'landing',
        'title' => $page_title ?? 'AI Generated Landing Page',
        'field_hide_page_title' => 1,
        'status' => 1,
      ]);

      // Log node initial state
      $this->loggerFactory->get('drupalx_ai')->debug('Initial node state - UUID: @uuid, EntityId: @id', [
        '@uuid' => $node->uuid(),
        '@id' => $node->id(),
      ]);

      $this->loggerFactory->get('drupalx_ai')->info('Created node entity, adding @count paragraphs', ['@count' => count($paragraphs)]);

      // Log paragraph data before processing
      $this->loggerFactory->get('drupalx_ai')->debug('Paragraph data to process: @data', [
        '@data' => json_encode($paragraphs),
      ]);

      foreach ($paragraphs as $index => $paragraphData) {
        $this->loggerFactory->get('drupalx_ai')->debug('Processing paragraph @index of type @type', [
          '@index' => $index,
          '@type' => $paragraphData['type'] ?? 'unknown',
        ]);

        $paragraph = $this->createParagraphFromGeneratedContent($paragraphData);
        if ($paragraph) {
          // Log paragraph creation success
          $this->loggerFactory->get('drupalx_ai')->debug('Created paragraph of type @type with ID @id', [
            '@type' => $paragraph->bundle(),
            '@id' => $paragraph->id(),
          ]);

          $node->get('field_content')->appendItem($paragraph);
          $this->loggerFactory->get('drupalx_ai')->debug('Successfully added paragraph @index to node', ['@index' => $index]);
        } else {
          $this->loggerFactory->get('drupalx_ai')->warning('Failed to create paragraph @index from data: @data', [
            '@index' => $index,
            '@data' => json_encode($paragraphData),
          ]);
        }
      }

      // Log field content state
      $this->loggerFactory->get('drupalx_ai')->debug('Node field_content state: @state', [
        '@state' => json_encode($node->get('field_content')->getValue()),
      ]);

      $violations = $node->validate();
      if (count($violations) > 0) {
        $violationMessages = [];
        foreach ($violations as $violation) {
          $violationMessages[] = $violation->getMessage();
        }
        $this->loggerFactory->get('drupalx_ai')->error('Node validation failed: @messages', [
          '@messages' => implode(', ', $violationMessages),
        ]);
        return NULL;
      }

      $this->loggerFactory->get('drupalx_ai')->info('Node validation passed, attempting to save');

      // Log pre-save node state
      $this->loggerFactory->get('drupalx_ai')->debug('Pre-save node state: @state', [
        '@state' => json_encode([
          'uuid' => $node->uuid(),
          'id' => $node->id(),
          'title' => $node->getTitle(),
          'type' => $node->bundle(),
          'status' => $node->isPublished(),
        ]),
      ]);

      $node->save();

      // Log post-save node state
      $this->loggerFactory->get('drupalx_ai')->debug('Post-save node state: @state', [
        '@state' => json_encode([
          'uuid' => $node->uuid(),
          'id' => $node->id(),
          'title' => $node->getTitle(),
          'type' => $node->bundle(),
          'status' => $node->isPublished(),
          'revision_id' => $node->getRevisionId(),
        ]),
      ]);

      $this->loggerFactory->get('drupalx_ai')->info('Successfully saved node with ID: @id', ['@id' => $node->id()]);

      // Verify the node exists after save
      $loadedNode = Node::load($node->id());
      if (!$loadedNode) {
        $this->loggerFactory->get('drupalx_ai')->error('Node could not be loaded after save with ID: @id', ['@id' => $node->id()]);
        return NULL;
      }

      // Log loaded node state
      $this->loggerFactory->get('drupalx_ai')->debug('Loaded node state: @state', [
        '@state' => json_encode([
          'uuid' => $loadedNode->uuid(),
          'id' => $loadedNode->id(),
          'title' => $loadedNode->getTitle(),
          'type' => $loadedNode->bundle(),
          'status' => $loadedNode->isPublished(),
          'revision_id' => $loadedNode->getRevisionId(),
        ]),
      ]);

      $this->loggerFactory->get('drupalx_ai')->info('Successfully verified node exists with ID: @id', ['@id' => $node->id()]);

      $url = Url::fromRoute('entity.node.edit_form', ['node' => $node->id()]);
      $absoluteUrl = $url->setAbsolute()->toString();

      $this->loggerFactory->get('drupalx_ai')->info('Generated URL for node: @url', ['@url' => $absoluteUrl]);

      return $absoluteUrl;
    }
    catch (\Exception $e) {
      $this->loggerFactory->get('drupalx_ai')->error('Failed to create landing page: @message', ['@message' => $e->getMessage()]);
      $this->loggerFactory->get('drupalx_ai')->error('Exception trace: @trace', ['@trace' => $e->getTraceAsString()]);
      return NULL;
    }
  }

  /**
   * Creates a paragraph entity from generated content.
   *
   * @param array $paragraphData
   *   The generated data for a single paragraph.
   * @param string $parentType
   *   The type of the parent paragraph (optional).
   *
   * @return \Drupal\paragraphs\Entity\Paragraph|null
   *   The created paragraph entity, or null if creation failed.
   */
  private function createParagraphFromGeneratedContent(array $paragraphData, string $parentType = ''): ?Paragraph {
    try {
      // Handle the case where '{' is used instead of 'type'.
      if (!isset($paragraphData['type']) && isset($paragraphData['{'])) {
        $paragraphData['type'] = $paragraphData['{'];
        unset($paragraphData['{']);
      }

      // Infer type based on parent type and field name
      if (!isset($paragraphData['type'])) {
        if ($parentType === 'pricing' || str_contains($parentType, 'pricing')) {
          $paragraphData['type'] = 'pricing_card';
        }
        elseif ($parentType === 'card_group' || str_contains($parentType, 'card')) {
          $paragraphData['type'] = 'card';
        }
        elseif ($parentType === 'carousel' || str_contains($parentType, 'carousel')) {
          $paragraphData['type'] = 'carousel_item';
        }
        elseif ($parentType === 'accordion' || str_contains($parentType, 'accordion')) {
          $paragraphData['type'] = 'accordion_item';
        }
      }

      if (!isset($paragraphData['type'])) {
        $this->loggerFactory->get('drupalx_ai')->warning('Paragraph type is missing and could not be inferred from parent type @parent. Skipping this paragraph.', [
          '@parent' => $parentType,
        ]);
        return NULL;
      }

      $this->loggerFactory->get('drupalx_ai')->debug('Creating paragraph of type @type with parent type @parent', [
        '@type' => $paragraphData['type'],
        '@parent' => $parentType ?: 'none',
      ]);

      $paragraph = Paragraph::create([
        'type' => $paragraphData['type'],
      ]);

      $fieldDefinitions = $paragraph->getFieldDefinitions();

      foreach ($paragraphData['fields'] as $fieldName => $fieldValue) {
        $fieldDefinition = $fieldDefinitions[$fieldName] ?? NULL;

        if (!$fieldDefinition) {
          $this->loggerFactory->get('drupalx_ai')->warning('Field @field does not exist for paragraph type @type', [
            '@field' => $fieldName,
            '@type' => $paragraphData['type'],
          ]);
          continue;
        }

        $this->loggerFactory->get('drupalx_ai')->debug('Processing field @field of type @type with value: @value', [
          '@field' => $fieldName,
          '@type' => $fieldDefinition->getType(),
          '@value' => is_array($fieldValue) ? json_encode($fieldValue) : $fieldValue,
        ]);

        // Skip this svg field.
        if ($fieldName === 'field_logo') {
          continue;
        }
        elseif ($fieldDefinition && $fieldDefinition->getType() === 'entity_reference' && $fieldDefinition->getSetting('target_type') === 'media') {
          if (is_string($fieldValue)) {
            $media = $this->createOrFetchMedia($this->preprocessImageSearchTerm($fieldValue));
            if ($media) {
              $paragraph->set($fieldName, $media);
            }
          }
          elseif (is_array($fieldValue)) {
            $mediaItems = [];
            foreach ($fieldValue as $value) {
              $media = $this->createOrFetchMedia($this->preprocessImageSearchTerm($value));
              if ($media) {
                $mediaItems[] = $media;
              }
            }
            if (!empty($mediaItems)) {
              $paragraph->set($fieldName, $mediaItems);
            }
          }
        }
        elseif (is_array($fieldValue) && (isset($fieldValue[0]['type']) || isset($fieldValue[0]['{']))) {
          // This is likely a nested paragraph field.
          $this->loggerFactory->get('drupalx_ai')->debug('Processing nested paragraphs for field @field in @type paragraph', [
            '@field' => $fieldName,
            '@type' => $paragraphData['type'],
          ]);

          $nestedParagraphs = [];
          foreach ($fieldValue as $index => $nestedParagraphData) {
            $this->loggerFactory->get('drupalx_ai')->debug('Processing nested paragraph @index with data: @data', [
              '@index' => $index,
              '@data' => json_encode($nestedParagraphData),
            ]);

            // Pass the current paragraph type as the parent type for nested paragraphs.
            $nestedParagraph = $this->createParagraphFromGeneratedContent($nestedParagraphData, $paragraphData['type']);
            if ($nestedParagraph) {
              $nestedParagraphs[] = $nestedParagraph;
              $this->loggerFactory->get('drupalx_ai')->debug('Successfully created nested paragraph @index of type @type', [
                '@index' => $index,
                '@type' => $nestedParagraph->bundle(),
              ]);
            } else {
              $this->loggerFactory->get('drupalx_ai')->error('Failed to create nested paragraph @index', [
                '@index' => $index,
              ]);
            }
          }

          // Check if this is a required field
          $isRequired = $fieldDefinition->isRequired();

          // If the field is required and we have no valid nested paragraphs, return NULL
          if ($isRequired && empty($nestedParagraphs)) {
            $this->loggerFactory->get('drupalx_ai')->error('Required nested paragraph field @field has no valid paragraphs', [
              '@field' => $fieldName,
            ]);
            return NULL;
          }

          // Only set the field if we have valid nested paragraphs
          if (!empty($nestedParagraphs)) {
            $this->loggerFactory->get('drupalx_ai')->debug('Setting @count nested paragraphs to field @field', [
              '@count' => count($nestedParagraphs),
              '@field' => $fieldName,
            ]);

            $paragraph->set($fieldName, $nestedParagraphs);

            // Log the field value after setting
            $this->loggerFactory->get('drupalx_ai')->debug('Field @field value after setting nested paragraphs: @value', [
              '@field' => $fieldName,
              '@value' => json_encode($paragraph->get($fieldName)->getValue()),
            ]);
          }
        }
        elseif ($fieldName === 'field_icon') {
          $iconName = $this->paragraphStructureService->getBestIconMatch($fieldValue);
          $paragraph->set($fieldName, $iconName);
        }
        elseif ($fieldName === 'field_features_text') {
          $cleanedFieldValue = preg_replace('/^[\W_]+/m', '', $fieldValue);
          $paragraph->set($fieldName, $cleanedFieldValue);
        }
        elseif ($fieldName === 'field_hero_layout') {
          // Check if the value is in the allowed list
          $allowedValues = $fieldDefinition->getSetting('allowed_values');
          if ($allowedValues && !isset($allowedValues[$fieldValue])) {
            $this->loggerFactory->get('drupalx_ai')->warning('Invalid hero layout value: @value. Allowed values: @allowed', [
              '@value' => $fieldValue,
              '@allowed' => implode(', ', array_keys($allowedValues)),
            ]);
            $fieldValue = 'image_top';
          }
          $paragraph->set($fieldName, !empty($fieldValue) ? $fieldValue : 'image_top');
        }
        elseif ($fieldName === 'field_text_layout') {
          // Check if the value is in the allowed list
          $allowedValues = $fieldDefinition->getSetting('allowed_values');
          if ($allowedValues && !isset($allowedValues[$fieldValue])) {
            $this->loggerFactory->get('drupalx_ai')->warning('Invalid text layout value: @value. Allowed values: @allowed', [
              '@value' => $fieldValue,
              '@allowed' => implode(', ', array_keys($allowedValues)),
            ]);
            $fieldValue = 'left';
          }
          $paragraph->set($fieldName, !empty($fieldValue) ? $fieldValue : 'left');
        }
        elseif ($fieldName === 'field_sidebyside_layout') {
          // Check if the value is in the allowed list
          $allowedValues = $fieldDefinition->getSetting('allowed_values');
          if ($allowedValues && !isset($allowedValues[$fieldValue])) {
            $this->loggerFactory->get('drupalx_ai')->warning('Invalid sidebyside layout value: @value. Allowed values: @allowed', [
              '@value' => $fieldValue,
              '@allowed' => implode(', ', array_keys($allowedValues)),
            ]);
            $fieldValue = 'left';
          }
          $paragraph->set($fieldName, !empty($fieldValue) ? $fieldValue : 'left');
        }
        else {
          if ($fieldDefinition && in_array($fieldDefinition->getType(), ['text', 'text_long', 'text_with_summary'])) {
            // Handle text fields that can come in either as string or array
            // format.
            if (is_array($fieldValue) && isset($fieldValue['value'])) {
              // If it's an array with 'value' key, use that value.
              $textValue = $fieldValue['value'];
              // Get the format if provided, default to 'basic_html'.
              $format = $fieldValue['format'] ?? 'basic_html';
              $paragraph->set($fieldName, [
                'value' => $this->convertRichTextFormat($textValue),
                'format' => $format,
              ]);
            } else {
              // If it's a string or any other format, convert it directly.
              $paragraph->set($fieldName, [
                'value' => $this->convertRichTextFormat((string) $fieldValue),
                'format' => 'basic_html',
              ]);
            }
          }
          elseif ($fieldDefinition->getType() === 'list_string') {
            // For list_string fields, verify the value is in the allowed list
            $allowedValues = $fieldDefinition->getSetting('allowed_values');
            if ($allowedValues && !isset($allowedValues[$fieldValue])) {
              $this->loggerFactory->get('drupalx_ai')->warning('Invalid value for list field @field: @value. Allowed values: @allowed', [
                '@field' => $fieldName,
                '@value' => $fieldValue,
                '@allowed' => implode(', ', array_keys($allowedValues)),
              ]);
              continue;
            }
            $paragraph->set($fieldName, $fieldValue);
          }
          else {
            // For non-text fields, set the value directly.
            $paragraph->set($fieldName, $fieldValue);
          }
        }

        // Validate the field after setting
        $violations = $paragraph->validate()->getByField($fieldName);
        if (count($violations) > 0) {
          $messages = [];
          foreach ($violations as $violation) {
            $messages[] = $violation->getMessage();
          }
          $this->loggerFactory->get('drupalx_ai')->error('Field @field validation failed for paragraph type @type: @messages', [
            '@field' => $fieldName,
            '@type' => $paragraphData['type'],
            '@messages' => implode(', ', $messages),
          ]);
        }
      }

      $violations = $paragraph->validate();
      if (count($violations) > 0) {
        $violationMessages = [];
        foreach ($violations as $violation) {
          $violationMessages[] = $violation->getMessage();
          $this->loggerFactory->get('drupalx_ai')->error('Validation error for field @field: @message', [
            '@field' => $violation->getPropertyPath(),
            '@message' => $violation->getMessage(),
          ]);
        }
        $this->loggerFactory->get('drupalx_ai')->error('Paragraph validation failed: @messages', [
          '@messages' => implode(', ', $violationMessages),
        ]);
        return NULL;
      }

      $this->loggerFactory->get('drupalx_ai')->debug('Saving paragraph of type @type', [
        '@type' => $paragraph->bundle(),
      ]);

      $paragraph->save();

      $this->loggerFactory->get('drupalx_ai')->debug('Successfully saved paragraph of type @type with ID @id', [
        '@type' => $paragraph->bundle(),
        '@id' => $paragraph->id(),
      ]);

      return $paragraph;
    }
    catch (\Exception $e) {
      $this->loggerFactory->get('drupalx_ai')->error('Failed to create paragraph: @message', ['@message' => $e->getMessage()]);
      $this->loggerFactory->get('drupalx_ai')->error('Exception trace: @trace', ['@trace' => $e->getTraceAsString()]);
      return NULL;
    }
  }

  /**
   * Converts markdown-like syntax and newlines in rich text.
   */
  private function convertRichTextFormat(string $text): string {
    // Convert **text** to <strong>text</strong>.
    $text = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $text);

    // Convert consecutive dash-prefixed lines to an unordered list.
    $text = preg_replace_callback(
      '/(?:^|\n)(-\s*.*(?:\n|$))+/',
      function ($matches) {
        $items = preg_split('/\n-\s*/', trim($matches[0]));
        $items = array_filter(array_map('trim', $items));
        return '<ul><li>' . implode('</li><li>', array_map(function ($item) {
          return ltrim($item, '- ');
        }, $items)) . '</li></ul>';
      },
      $text
    );

    // Convert remaining single newlines to <br> tags.
    $text = preg_replace('/(?<!\n)\n(?!\n)/', '<br>', $text);

    return $text;
  }

  /**
   * Preprocesses an image search term.
   *
   * @param mixed $term
   *   The search term to preprocess.
   *
   * @return string
   *   The preprocessed search term.
   */
  private function preprocessImageSearchTerm(mixed $term): string {
    if (is_array($term)) {
      // Flatten the array and convert all elements to strings.
      $term = array_map(function ($item) {
        return is_array($item) ? implode(' ', $item) : (string) $item;
      }, $term);
      $term = implode(' ', $term);
    }

    $term = (string) $term;
    $term = trim($term);
    $term = strtolower($term);
    return preg_replace('/[^a-z0-9\s]/', ' ', $term);
  }

  /**
   * Creates or fetches a media entity based on a search term.
   *
   * @param string $searchTerm
   *   The search term to use for finding or creating media.
   *
   * @return int|null
   *   The media entity ID if successful, null otherwise.
   */
  private function createOrFetchMedia(string $searchTerm) {
    $config = $this->configFactory->get('drupalx_ai.settings');
    $imageGenerator = $config->get('image_generator') ?: 'placeholder';

    try {
      $newMedia = NULL;
      if ($imageGenerator === 'unsplash') {
        $newMedia = (int) $this->mockLandingPageService->createMediaEntityFromUnsplash($searchTerm);
      }
      elseif ($imageGenerator === 'pexels') {
        $newMedia = (int) $this->mockLandingPageService->createMediaEntityFromPexels($searchTerm);
      }
      elseif ($imageGenerator === 'tavily') {
        $newMedia = $this->mockLandingPageService->createMediaEntityFromTavily($searchTerm);
      }

      // Default to placeholder image.
      if (empty($newMedia)) {
        $newMedia = (int) $this->mockLandingPageService->getMediaEntityPlaceholder($searchTerm);
      }

      if ($newMedia) {
        $this->loggerFactory->get('drupalx_ai')->info('Successfully created new media entity for search term: @term using @generator', [
          '@term' => $searchTerm,
          '@generator' => $imageGenerator,
        ]);
        return $newMedia;
      }
      $this->loggerFactory->get('drupalx_ai')->warning('Failed to create new media entity for search term: @term using @generator', [
        '@term' => $searchTerm,
        '@generator' => $imageGenerator,
      ]);
    }
    catch (\Exception $e) {
      $this->loggerFactory->get('drupalx_ai')->error('Exception while creating media entity: @message', ['@message' => $e->getMessage()]);
    }

    // If creation fails or returns null, fall back to finding an existing media item.
    $mediaStorage = $this->entityTypeManager->getStorage('media');
    $existingMedia = $mediaStorage->loadByProperties([
      'name' => $searchTerm,
      'bundle' => 'image',
    ]);

    if (!empty($existingMedia)) {
      return reset($existingMedia)->id();
    }

    // If no existing media found either, return null.
    return NULL;
  }

}
